### ISSUE TITLE
arXiv

### ISSUE THREAD

**Issue by gugushvili** [BibBase/bibbase.github.io#1]
To download BibTeX entries of my arXiv submissions I use the NASA ADS service. A typical [entry](http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1805.05606) would be

@ARTICLE{2018arXiv180505606G,
   author = {{Gugushvili}, S. and {van der Meulen}, F. and {Schauer}, M. and 
	{Spreij}, P.},
    title = "{Nonparametric Bayesian volatility learning under microstructure noise}",
  journal = {ArXiv e-prints},
archivePrefix = "arXiv",
   eprint = {1805.05606},
 primaryClass = "stat.ME",
 keywords = {Statistics - Methodology, Quantitative Finance - Statistical Finance, Statistics - Machine Learning, Primary: 62G20, Secondary: 62M05},
     year = 2018,
    month = may,
   adsurl = {http://adsabs.harvard.edu/abs/2018arXiv180505606G},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

However, since there is no volume available in the entry, I get an annoying break in the html version after _ArXiv e-prints_, followed by a dot. For instance,

Gugushvili, S.; van der Meulen , F.; Schauer, M.; and Spreij, P. **Nonparametric Bayesian volatility learning under microstructure noise.** _ArXiv e-prints_, . May 2018.

Is there a fix for this? (obviously other than manually modifying the format of BibTeX entries)

Thanks!

**Comment by chfritz** [comment]
Thanks for reporting. We've changed the layout for articles now to not include a break when there is neither a volume nor a number specified.

BTW, this repository is not the best place to report issues or ask questions about BibBase. It is just a template for new users to fork, so they can get started more quickly. For issues and questions, please use the support forum and ticket system: https://bibbase.userecho.com
