### ISSUE TITLE
I replaced the bibtex file but the website still shows the old one

### ISSUE THREAD

**Issue by wsolorza** [BibBase/bibbase.github.io#9]
Is there a delay?

https://wsolorza.github.io/
https://github.com/wsolorza/wsolorza.github.io

**Comment by chfritz** [comment]
Not from bibbase's side, but github pages only refresh every 15 minutes or so. Bibbase does cache your bibtex file and always serves the publication list from cache for performance reasons, but also updates the cache on every page load. So reloading the page twice with a short delay (few seconds) always give you the latest.
